VERSION="2.0.0" 
 
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015" 
 
ACCOUNTS=[ 
"GAHHULDPDVGB5WS5PH7BCGLJ7ZHECDBIIMKB62UPVDUOCHNFL7HX3FS7" 
] 
 
[DOCUMENTATION] 
ORG_NAME="authentic-Payment" 
ORG_URL="https://authentic-payment.com/" 
ORG_LOGO=" https://authentic-payment.com/wp-content/uploads/2022/07/cropped-cropped-2080px-galaxy-white-v2-glow-nobg.png" 
ORG_DESCRIPTION="authentic-payment is a digital enterprise that offers multiple services & products. while focussing, building & exploring on possibilities inside of the cryptocurrency space we thought of shaping a project that provides small services like media/brand design, editing & setups for a digital work environment. with the coming application we will give you a safe and secure wallet to store your Authentic-Payment token $Apay, $xlm or other native assets. with more exposure, daily volume & liquidity we can improve the App to a multi chain wallet and who knows where the limit is. Authentic-payment.com" 
ORG_KEYBASE="Appahhhh" 
ORG_TWITTER="@OfficialApay" 
ORG_OFFICIAL_EMAIL="Support@authentic-payment.com" 
 
[[CURRENCIES]] 
code="AXLM" 
issuer="GAHHULDPDVGB5WS5PH7BCGLJ7ZHECDBIIMKB62UPVDUOCHNFL7HX3FS7"
 
display_decimals="5"
is_asset_anchored=false 
name="ApayXLM" 
desc="1:1 xlm backed token created by Authentic-Payment. supply is determined on ask & demand. move your $AXLM to your favourite wallet and be able to claim your $XLM back while recieving $Apay reward " 
conditions="$AXLM has a starting supply of 10.000.000 (10million). supply is determined by ask & demand" 
image="https://authentic-payment.com/wp-content/uploads/2022/09/photo_2022-09-07-10.42.02.jpeg" 
status="live"
  
# Home Domain:authentic-payment.com 
# Authentic-Payment Token
